### ISSUE TITLE
Telepítési útmutató

### ISSUE THREAD

**Issue by Saboteur777** [rrd108/ps-utanvet-ellenor#1]
Mit és hova kell tenni a telepítéshez?

**Comment by rrd108** [comment]
letöltöd zipként és a ps-ben bemész a Modul Catalogue-ba és felül modul hozzáadása.

**Comment by Saboteur777** [comment]
Letöltöttem a 0.0.2-es tag-hez tartozó ZIP-et, megpróbáltam feltölteni, viszont hibát ír ki: 

![image](https://user-images.githubusercontent.com/9061795/103177569-fc89d200-487b-11eb-8971-d6abbc724806.png)

**Comment by rrd108** [comment]
jogos, a githib zip-je nem lesz egyből használható. Itt a link: https://webmania.cc/downloads/ps-utanvetellenor

**Comment by Saboteur777** [comment]
@rrd108 Ezen a linken nem találom, csak a bejegyzések listáját látom.

**Comment by rrd108** [comment]
Hm...

It egy másik link: https://webmania.cc/sdm_downloads/ps-utanvet-ellenor/

**Comment by Saboteur777** [comment]
Szuper, most már rendben települt - köszi! :)
