### ISSUE TITLE
JSON file for updates

### ISSUE THREAD

**Issue by Saboteur777** [rrd108/ps-utanvet-ellenor#11]
A json fájlnak ilyen formátumúnak kell lennie: 

```json
{
    "name" : "Prestashop Utánvétellenőr modul",
    "version" : "0.0.3",
    "last_updated" : "2020-12-28",
    "download_url" : "https://webmania.cc/downloads/ps-utanvetellenor",
    "homepage" : "https://webmania.cc"
}
```

**Comment by Saboteur777** [comment]
@rrd108 Ez is megvan: https://github.com/rrd108/ps-utanvet-ellenor/commit/90e0702c7966c83af2cf047d4c46c4b48ec392f7

A [GitHub API](https://api.github.com/repos/rrd108/ps-utanvet-ellenor/releases/latest)-tól veszi az infókat egy controller az utanvet-ellenor.hu-n és átfordítja a megfelelő formátumra az adatokat: https://utanvet-ellenor.hu/api/v1/plugins/prestashop

```
{"name":"Utánvét Ellenőr PrestaShop modul","version":"v1.0.10","last_updated":"2020-12-30T12:57:00Z","download_url":"https://github.com/rrd108/ps-utanvet-ellenor/releases/download/v1.0.10/utanvetellenor.zip","homepage":"https://utanvet-ellenor.hu/"}
```

Ennek megfelelően frissítettem a modult és kiadtam belőle egy újabb verziót.

**Comment by rrd108** [comment]
A verzió számból ki kell venni a "v"-t mert így el fog hasalni az összehasonlítás.

**Comment by Saboteur777** [comment]
Oké, megvan.
