### ISSUE TITLE
Utanvetellenor listed at payment list 

### ISSUE THREAD

**Issue by rrd108** [rrd108/ps-utanvet-ellenor#12]
https://github.com/rrd108/ps-utanvet-ellenor/blob/d7f2790c400c9521ca29c78ae86caf8141be9d03/utanvetellenor.php#L174

Itt nekem visszaadja az utánvétellenőrt is.

1.7.6

Bár lehet hogy csak azért mert az egyik korai verzióban payment modulként volt definiálva. Egy clean installal ellenőrizhető.

**Comment by Saboteur777** [comment]
Nálam semmi ilyen jelenség nem volt, többször is újratelepítettem a rendszert. Kérlek, nézd meg, hogy nulláról indulva is fellép-e a hiba, ha igen, nyisd újra ezt az issue-t, addig is zárom.
