### ISSUE TITLE
Folder name in releases prevents drag'n'drop installation in PrestaShop

### ISSUE THREAD

**Issue by Saboteur777** [rrd108/ps-utanvet-ellenor#6]

**Comment by Saboteur777** [comment]
@rrd108  Ma elég sokat dolgoztam a modulon, jelentős részét átírtam, kérlek, teszteld le te is, ha találsz benne hibát, szólj. 

Ha ezt az issue-t megoldottuk, akkor szerintem mehet a Prestashop csoportba a megosztás (ez melyik FB csoport egyébként?).

**Comment by rrd108** [comment]
Ezzel nem tudunk mit kezdeni, csak azt, hogy nem a github-ot adjuk meg letöltési felületként hanem mást, ahol kontrollálni tudjuk a zip-et. Lehet közvetlen az utanvet-ellenor.hu, vagy a webmania.cc, vagy amit akarsz.
Mivel nem kerül be a hivatalos áruházba a frissítéseket csak a modul beállítások oldalán tudjuk jelezni, tehát a zip file mellet egy josn filet is hosztolni kell.

**Comment by Saboteur777** [comment]
A json fájlnak gondolom ilyen formátumnak kell lennie: 

```json
{
    "name" : "Prestashop Utánvétellenőr modul",
    "version" : "0.0.3",
    "last_updated" : "2020-12-28",
    "download_url" : "https://webmania.cc/downloads/ps-utanvetellenor",
    "homepage" : "https://webmania.cc"
}
```

Amit viszont nem értek, hogy az itt megadott `download_url` link nekem 404-et ad vissza, ott magának a ZIP fájlnak kellene lennie?

**Comment by rrd108** [comment]
igen, pontosan. Ennél nem módosítottam a dowload url-t mert csak a tesztekhez kellett. Jó ha az url vagy a zip filera mutat.

**Comment by Saboteur777** [comment]
> Ezzel nem tudunk mit kezdeni, csak azt, hogy nem a github-ot adjuk meg letöltési felületként hanem mást, ahol kontrollálni tudjuk a zip-et.

@rrd108 Megoldottam - minden olyan push esetén, amikor tag jön, az adott tag-re le fog futni egy build folyamat, ami során készül egy release (ami már a PrestaShop számára is fogyasztható formátumú zip), ami felkerül ide: https://github.com/rrd108/ps-utanvet-ellenor/releases

A legutolsó release-re lehet hivatkozni így is: https://github.com/rrd108/ps-utanvet-ellenor/releases/latest, ezt tettem be a README.md-be.

Már csak a JSON fájlra kell megoldást találni.
