### ISSUE TITLE
missing default settings

### ISSUE THREAD

**Issue by rrd108** [rrd108/ps-utanvet-ellenor#8]
@Saboteur777 
Direkt vetted ki a beállításoknál a default értékeket? 

Sikeres státusz, Visszautasított státus, Elrejtendő fizetési módok - ezeknek én mindenképpen adnék default értéket, de a magam részéről a Megbízhatósági mutató-nak is, ami most nincs is required-re állítva.

**Comment by rrd108** [comment]
Az utánvételenőr opciót az elrejtendők között nem kéne megjeleníteni

**Comment by Saboteur777** [comment]
Igen, direkt: pont azért, hogy kénytelen legyen beállítani az értékeket, ne utólag jöjjön rá, hogy ja-hogy-ja. 

> "Az utánvételenőr opciót az elrejtendők között nem kéne megjeleníteni" 

Mire gondolsz?

**Comment by Saboteur777** [comment]
A threshold mezőt már kötelezőnek jelöli: https://github.com/rrd108/ps-utanvet-ellenor/commit/e4216a286ad51945a3be7f05e35ff26d3dc14a2c

(Viszont valamiért engedi üresen is elküldeni... -.- )

**Comment by Saboteur777** [comment]
A sikeres és visszautasított státuszokat automatikusan beállítjuk nekik telepítés közben: 

https://github.com/rrd108/ps-utanvet-ellenor/blob/main/utanvetellenor.php#L75
https://github.com/rrd108/ps-utanvet-ellenor/blob/main/utanvetellenor.php#L79

**Comment by rrd108** [comment]
> Igen, direkt: pont azért, hogy kénytelen legyen beállítani az értékeket, ne utólag jöjjön rá, hogy ja-hogy-ja.

PS körökben hozzá vannak szokva a defaultokhoz. És ha gyári státuszokat állítunk be (illetve azt amit a modul hoz létre) akkor biztosra mentünk.

**Comment by rrd108** [comment]
> Az utánvételenőr opciót az elrejtendők között nem kéne megjeleníteni

Ahol ki lehet választani, hogy melyikeket rejtse el ott ezt is felsorolja, pedig nem kéne.

**Comment by Saboteur777** [comment]
![image](https://user-images.githubusercontent.com/9061795/103351117-769ba000-4aa2-11eb-9725-1c6e2eee117d.png)

Én ezt látom, mire gondolsz? 

> PS körökben hozzá vannak szokva a defaultokhoz. És ha gyári státuszokat állítunk be (illetve azt amit a modul hoz létre) akkor biztosra mentünk.

Igen, a kód ezt teszi a fenti linkeken: 
- a 4-es ID-jú státuszt állítja be a 75. sorban, 
- a `createRefusedOrderState()` által visszaadott ID-t állítjuk be a 79. sorban, ami az újabb státusz létrehozása előtt megnézi, hogy van-e olyan OrderState, aminél az `utanvetellenor` a `module_name`, mert azt akkor mi hoztuk létre. Ha van, akkor annak az ID-ját adja vissza.
